### ISSUE TITLE
Duplicated select inputs don't carry selection

### ISSUE THREAD

**Issue by wisend** [gr2m/navigable-table#8]
Duplicated select inputs don't carry the user selections. The default value is set to the first option in the select list unless an option has the `selected` attribute applied.

This can be seen on the demo [http://gr2m.github.io/navigable-table/](http://gr2m.github.io/navigable-table/) by changing 'Dawn Robinson' to male and duplicating the row.

**Comment by gr2m** [comment]
what browser are you testing in? I was not able to reprodue the issue in latest Chrome and Firefox.

Here is what I do:

2. Change female to male using the mouse in the row of Dawn Robinson
3. Set cursor in Dawn Robinson
3. Hit command + d

Outcome is the new row has the gender set to male

**Comment by wisend** [comment]
Sorry, my mistake! I was using alt + enter instead of alt + d.
